### ISSUE TITLE
BQS Model01 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/bo-quadrupoles-qs#1]
bo-quadrupoles-qs/model-01/simulation/magnetic/2017-04-05_BQS_Model01_Sim_X=-20_20mm_Z=-300_300mm_Imc=9.64A.txt

**Comment by xresende** [comment]
fmap analyzed. integrated skew gradient spec achieved. DA calculation pending.

**Comment by xresende** [comment]
Just remembered that we have not yet defined any simulation that uses the skew quadrupole with which we can test the magnets multipoles. but they all came out relatively small and are approved.
